SELECT WAIT_CLASS, TOTAL_WAITS, round(100*(TOTAL_WAITS/SUM_WAITS),2) PCT_TOTAL_WAITS,
ROUND((TIME_WAITED/100),2) TIME_WAITED, round(100*(TIME_WAITED/SUM_TIME_WAITED),2) PCT_TIME_WAITED
FROM (SELECT WAIT_CLASS, TOTAL_WAITS, TIME_WAITED FROM V$SYSTEM_WAIT_CLASS WHERE WAIT_CLASS != 'Idle'),
(SELECT sum(TOTAL_WAITS) SUM_WAITS, sum(TIME_WAITED) SUM_TIME_WAITED FROM V$SYSTEM_WAIT_CLASS WHERE WAIT_CLASS != 'Idle')
ORDER BY PCT_TIME_WAITED DESC
