SELECT EVENT, TIME_WAITED, round(100*(TIME_WAITED/SUM_TIME_WAITED),2) PCT_TIME_WAITED,
TOTAL_WAITS, round(100*(TOTAL_WAITS/SUM_TOTAL_WAITS),2) PCT_TOTAL_WAITS
FROM (SELECT EVENT, TIME_WAITED, TOTAL_WAITS FROM V$SYSTEM_EVENT),
(SELECT sum(TIME_WAITED) SUM_TIME_WAITED, sum(TOTAL_WAITS) SUM_TOTAL_WAITS FROM V$SYSTEM_EVENT)
WHERE ROWNUM<=10
ORDER BY PCT_TIME_WAITED DESC
